import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {Simulation} from '../src/simulation.js';import {ICHOR,nextIchorCut,ichorEndSide} from '../src/weapons/ichor.js';import {ichorCutArc,ichorSpin} from '../src/weapons/ichor-cut.js';import {ichorMotion} from '../src/weapons/ichor-motion.js';import {makeIchor,poseIchor} from '../src/weapons/ichor-model.js';import {IchorView} from '../src/weapons/ichor-view.js';import {tryIchorDeflect,ichorGuardFor} from '../src/weapons/ichor-deflect.js';import {IchorDrench} from '../src/effects/ichor-drench.js';import {Wading} from '../src/effects/blood-wading.js';import {Arena} from '../src/net/arena.js';import {BotMatch} from '../src/bots/bot-match.js';import {packEvent} from '../src/net/protocol.js';import {SHARED_EVENTS} from '../src/net/host-session.js';
const map={id:'ichor-flow',width:70,depth:70,spawn:{x:0,z:0},buildings:[],fences:[],props:[],targets:[]};
const make=(blood=0)=>{const s=new Simulation(map);s.weapon='ichor';s.player.id='you';s.ichor.blood=blood;return s;};
const run=(s,n,input={})=>{for(let i=0;i<n;i++)s.step({aimX:1,aimZ:0,...input});};
const victim=(id='victim',z=0)=>({id,kind:'player',x:1.6,z,baseX:1.6,hp:400,maxHp:400,respawn:0,flash:0});
const guard=()=>({duration:.24,swing:.18,serial:1,parrySerial:-1,parryCooldown:0,cutX:-1,cutZ:0});
const round={owner:'shooter',bullet:true,damage:10,vx:1,vz:0};
function fxScene(ground){const s=make(),p=new THREE.Group();p.userData={gun:new THREE.Group(),body:new THREE.Group()};p.add(p.userData.gun);const v={player:p,scene:new THREE.Scene(),qualityName:'potato',ground:ground||s.ground,lastSim:s,rifleView:{pose:{update(){}}},remotePlayers:[],burst(){}};return {s,v,fx:new IchorView(v)};}
test('above 90 blood restores 1.2 per second, caps at health and pauses for all Frenzy ticks',()=>{for(const [blood,gain]of [[90,0],[90.01,1.2],[100,1.2]]){const s=make(blood);s.player.hp=80;run(s,60);assert.ok(Math.abs(s.player.hp-80-gain)<1e-7);}const s=make(100);s.player.hp=99.8;run(s,60);assert.equal(s.player.hp,100);s.player.hp=80;run(s,1,{ichorX:true});assert.equal(s.player.hp,80);while(s.ichor.frenzy>0){const before=s.player.hp;run(s,1);assert.ok(s.player.hp<=before+1e-7);}const after=s.player.hp;run(s,60);assert.ok(Math.abs(s.player.hp-after-1.2)<1e-7);s.player.hp=0;s.player.dead=true;run(s,60);assert.equal(s.player.hp,0);});
test('quick successful cuts gain at most 21 percent extra blood, multiple victims do not advance the streak',t=>{t.mock.method(Math,'random',()=>.5);for(const count of [1,2]){const s=make();s.targets=[victim(),...(count===2?[victim('second',.1)]:[])];let expected=0;for(let i=0;i<4;i++){run(s,1,{tapFire:true});run(s,14);expected+=7.5*(1+Math.min(i,3)*.07)*count;assert.ok(Math.abs(s.ichor.blood-expected)<1e-7);}assert.equal(s.ichor.chain,4);run(s,60);const before=s.ichor.blood;run(s,1,{tapFire:true});run(s,8);assert.equal(s.ichor.chain,1);assert.ok(Math.abs(s.ichor.blood-before-7.5*count)<1e-7);}});
test('base sequence starts from previous finishing side, varies guards and occasionally spins',()=>{const s={serial:0,normalIndex:0,variant:0},forms=[];for(let i=0;i<36;i++){const side=s.serial?ichorEndSide(s.variant):-1,v=nextIchorCut(s);assert.equal(v%2?1:-1,side);forms.push(v);s.variant=v;s.serial++;}assert.ok(forms.some(ichorSpin));assert.ok(forms.some(v=>ichorCutArc(v)<2));assert.ok(new Set(forms).size>=8);for(const v of [0,1,2,3,7,8,9]){const blade=makeIchor();let pose;for(let i=0;i<60;i++)pose=poseIchor(blade,{serial:1,variant:v,swing:0},i/60);assert.ok(Math.abs(pose.yaw-ichorMotion(v,1)[3])<.002);}});
test('slashing slows ordinary movement slightly while keeping WASD control',()=>{const cut=make(),walk=make();run(cut,1,{tapFire:true});run(cut,8,{moveZ:1});run(walk,8,{moveZ:1});assert.ok(cut.player.z<walk.player.z*.92);assert.ok(cut.player.z>walk.player.z*.8);assert.equal(cut.player.x,0);});
test('timed deflection needs an active crossing and a front-facing ordinary bullet',()=>{for(const age of [0,.03,.1,.23])assert.equal(tryIchorDeflect({...victim(),ichorGuard:{...guard(),swing:.24-age}},round),null);for(const type of ['ballast','omenShot','omenCurse','sightlineBreach','ichorWave'])assert.equal(tryIchorDeflect({...victim(),ichorGuard:guard()},{...round,damageType:type}),null);for(const extra of [{bullet:false},{electric:true},{blast:true},{vx:-1},{vx:0,vz:1}])assert.equal(tryIchorDeflect({...victim(),ichorGuard:guard()},{...round,...extra}),null);for(const type of [undefined,'gunshot','sidekickShot','sightlinePistol','sightlineShot']){const g=guard(),t={...victim(),ichorGuard:g},e=tryIchorDeflect(t,{...round,damageType:type},()=>.5);assert.ok(e&&e.dx<0&&Math.abs(e.dz)>.5);assert.equal(tryIchorDeflect({...t},round),null);g.serial++;assert.equal(tryIchorDeflect(t,round),null);g.parryCooldown=0;assert.ok(tryIchorDeflect(t,round));assert.ok(SHARED_EVENTS.has(e.type));assert.equal(packEvent(e).type,'ichorDeflect');}});
test('a deflected live Nominal bullet is consumed without damage, blood or hit credit',()=>{const s=make();s.weapon='rifle';const t={...victim(),ichorGuard:guard()};s.targets=[t];s.rifleBullets=[{id:999,x:1,z:0,dx:1,dz:0,travel:0,aimed:true}];run(s,1);assert.equal(t.hp,400);assert.equal(s.rifleBullets.length,0);const e=s.drainEvents();assert.equal(e.filter(e=>e.type==='ichorDeflect').length,1);assert.ok(!e.some(e=>e.type==='hit'||e.type==='kill'));});
test('host and bot proxies share the defender recovery so simultaneous attackers cannot each parry',()=>{const a=new Arena({map,createSim:m=>new Simulation(m),settings:{robots:'off'}}),one=a.addSeat('one','One'),two=a.addSeat('two','Two');for(const seat of [one,two]){seat.present=true;seat.sim.respawn({x:0,z:0},seat.id);}two.sim.weapon='ichor';Object.assign(two.sim.ichor,guard());a.before(one);const t=one.sim.targets.find(t=>t.id==='two');assert.equal(t.ichorGuard,two.sim.ichor);one.sim.hit(t,{...round,owner:'one'});a.after(one);assert.equal(two.sim.player.hp,100);a.before(one);one.sim.hit(one.sim.targets.find(t=>t.id==='two'),{...round,owner:'one'});a.after(one);assert.equal(two.sim.player.hp,90);const main=make(),bots=new BotMatch(map,{createSim:m=>new Simulation(m),random:()=>.4}),bot=bots.spawn(main,'ichor');Object.assign(bot.sim.ichor,guard());bots.before(main);const proxy=main.targets.find(t=>t.id===bot.id);assert.equal(proxy.ichorGuard,bot.sim.ichor);main.hit(proxy,round);bots.after(main);assert.equal(bot.sim.player.hp,100);assert.ok(bot.sim.ichor.parryCooldown>0);});
test('slash geometry follows rising ground and preserves lower bridge level and depth testing',()=>{const {s,fx}=fxScene({flat:false,heightAt:(x,z)=>x*.6+z*.2,drawnHeightAt:(x,z)=>x*.6+z*.2});fx.event({type:'ichorSwing',x:0,z:0,dx:1,dz:0,variant:4,serial:1,power:.4,duration:.24});fx.update(s,.15);const a=fx.ribbons.geometry.getAttribute('position');assert.ok(fx.ribbons.geometry.drawRange.count>0);for(let i=0;i<fx.ribbons.geometry.drawRange.count;i++)assert.ok(a.getY(i)>=a.getX(i)*.6+a.getZ(i)*.2+.23999);assert.equal(fx.ribbons.material.depthTest,true);const under=fxScene({flat:false,heightAt:()=>4,drawnHeightAt:()=>0});under.fx.event({type:'ichorSwing',x:0,z:0,dx:1,dz:0,variant:4,power:1,duration:.24,below:true});under.fx.update(under.s,.15);const p=under.fx.ribbons.geometry.getAttribute('position');for(let i=0;i<under.fx.ribbons.geometry.drawRange.count;i++)assert.ok(p.getY(i)<1.5);});
test('Frenzy detail and ricochet effects stay capped and clear without persistent geometry',()=>{const {s,fx}=fxScene();for(let i=0;i<40;i++){fx.event({type:'ichorSwing',x:0,z:0,dx:1,dz:0,variant:i%10,serial:i,beat:i%12,power:1,duration:.2,frenzy:true,finisher:true});fx.event({type:'ichorDeflect',x:0,z:0,dx:-1,dz:.3,range:4,y:.8});fx.event({type:'ichorFrenzyStart',x:0,z:0,power:1});}fx.update(s,.1);assert.ok(fx.ribbons.count>0&&fx.ribbons.count<=18000);assert.ok(fx.lines.count<=1800);assert.equal(fx.ricochets.length,24);assert.equal(fx.frenzyBursts.length,6);fx.clear();assert.equal(fx.ricochets.length+fx.frenzyBursts.length,0);assert.ok(fx.meshes.every(m=>m.count===0));});
test('full blood saturates existing avatar faces, preserves shared assets and tracks 24 wet steps',()=>{const w=new Wading();for(let i=0;i<60;i++)w.soakIchor(100,1/60);assert.equal(w.drench,1);assert.equal(w.wet,24);const prints=Array.from({length:25},()=>w.takePrint());assert.equal(prints.filter(Boolean).length,24);assert.ok(prints.every(v=>v>=0&&v<=1));const body=new THREE.Group(),geometry=new THREE.BoxGeometry(1,1,1),material=new THREE.MeshLambertMaterial({color:'#49716b'}),a=new THREE.Mesh(geometry,material),other=new THREE.Mesh(geometry,material);body.add(a);const tint=new IchorDrench(body);tint.set(1);assert.notEqual(a.geometry,geometry);assert.equal(other.geometry,geometry);assert.equal(other.material,material);const c=a.geometry.getAttribute('color');for(let i=0;i<c.count;i++)assert.ok(c.getX(i)>c.getY(i)*2);const count=body.children.length;tint.set(.5);assert.equal(body.children.length,count);let freed=0;a.geometry.addEventListener('dispose',()=>freed++);tint.clear();assert.equal(freed,1);assert.equal(a.geometry,geometry);assert.equal(a.material,material);w.reset();assert.equal(w.drench+w.wet,0);});

import {BloodDrops} from '../src/effects/blood-drops.js';
test('new soaked footprints keep their below-bridge level and reset their batch',()=>{const scene=new THREE.Scene(),drops=new BloodDrops({scene,qualityName:'potato',ground:{flat:false,heightAt:()=>4,drawnHeightAt:()=>-.2}}),m=new THREE.Matrix4();drops.print(0,0,0,1,map,true);drops.prints.getMatrixAt(0,m);assert.ok(Math.abs(m.elements[13]+.194)<1e-6);drops.clear();assert.equal(drops.prints.count,0);drops.dispose();assert.equal(scene.children.length,0);});

import {DeathCorpse} from '../src/effects/death-corpse.js';
test('a soaked corpse owns its blood colours after the living avatar resets and releases them on cleanup',()=>{const root=new THREE.Group(),body=new THREE.Group(),gun=new THREE.Group();root.add(body);const mesh=new THREE.Mesh(new THREE.BoxGeometry(.5,1,.5),new THREE.MeshLambertMaterial({color:'#49716b'}));body.add(mesh);root.userData.gun=gun;const tint=new IchorDrench(body);tint.set(1);root.updateMatrixWorld(true);const scene=new THREE.Scene(),view={player:root,scene,qualityName:'potato'},corpse=new DeathCorpse(view,{x:0,z:0,aimX:1,aimZ:0},{mode:'fallen'}),snapshot=corpse.geometries.find(g=>g.userData.ichorDrench);assert.ok(snapshot);assert.notEqual(snapshot,mesh.geometry);tint.clear();assert.ok(snapshot.getAttribute('color').getX(0)>snapshot.getAttribute('color').getY(0)*2);let disposed=0;snapshot.addEventListener('dispose',()=>disposed++);corpse.dispose();assert.equal(disposed,1);assert.equal(scene.children.length,0);});

test('a bloody missed cut sheds blood along the blade, never more while paused, and settles with bounded cleanup',()=>{const {s,fx,v}=fxScene();const e={type:'ichorSwing',x:0,z:0,dx:1,dz:0,variant:0,serial:1,power:1,duration:.24};fx.event(e);fx.update(s,.12);assert.ok(fx.bloodMotes.length>=8);const first=fx.bloodMotes.length;fx.update(s,0);fx.update(s,0);assert.equal(fx.bloodMotes.length,first);const stained=[];v.drops={stain:(...p)=>stained.push(p)};for(let i=0;i<60;i++)fx.update(s,1/60);assert.equal(fx.bloodMotes.length,0);assert.ok(stained.length>0);fx.clear();assert.equal(fx.lines.count,0);const dry=fxScene();dry.fx.event({...e,power:0});dry.fx.update(dry.s,.12);assert.equal(dry.fx.bloodMotes.length,0);});
test('bloodier player contacts create a larger spray while robot contacts remain bloodless',()=>{const {fx,v}=fxScene();let bleeds=0;v.bleed=()=>bleeds++;fx.hit({type:'hit',id:'human',targetKind:'player',damageType:'ichorSlash',damage:17,x:0,z:0,directionX:1,directionZ:0,bloodLevel:1});assert.ok(fx.bloodMotes.length>=60);assert.equal(bleeds,1);fx.clear();fx.hit({type:'hit',id:'robot',targetKind:'robot',damageType:'ichorSlash',damage:17,x:0,z:0,directionX:1,directionZ:0,bloodLevel:1});assert.equal(fx.bloodMotes.length,0);assert.ok(fx.sparks.length);});
test('normal blade reach is slightly shorter, with the existing dash extension retained',()=>{const s=make(),t=victim();t.x=2.75;s.targets=[t];run(s,1,{tapFire:true});run(s,12);assert.equal(t.hp,400);const dash=make(),d=victim();d.x=2.75;dash.targets=[d];dash.ichor.dashWindow=.2;run(dash,1,{tapFire:true});run(dash,12);assert.ok(d.hp<400);assert.equal(ICHOR.range,2.15);});

test('E needs at least half blood, does not spend blood, and recharges in six seconds',()=>{for(const blood of [0,49.99]){const s=make(blood);run(s,1,{ichorE:true});assert.equal(s.ichorWaves.length,0);assert.equal(s.ichor.eCooldown,0);assert.equal(s.ichor.serial,0);}const s=make(50);run(s,1,{ichorE:true});assert.equal(s.ichor.blood,50);assert.equal(s.ichor.eCooldown,6);assert.equal(s.ichorWaves.length,1);const w=s.ichorWaves[0];assert.ok(w.damage>=16-1e-9&&w.damage<=20+1e-9);/* 18 ± 2 since the 2026-09-30 balance pass (14 ± 2) */assert.ok(Math.abs(w.travel-19/60)<1e-8);run(s,120,{ichorE:true});assert.equal(s.drainEvents().filter(e=>e.type==='ichorWave').length,1);run(s,240);assert.ok(s.ichor.eCooldown<1e-8);run(s,1,{ichorE:true});assert.equal(s.drainEvents().filter(e=>e.type==='ichorWave').length,1);});

test('slash wakes and shed blood stay on the near side of solid cover',()=>{
 const {s,fx}=fxScene();s.colliders=[{x:.9,z:0,w:.25,d:8,height:2}];fx.event({type:'ichorSwing',x:0,z:0,dx:1,dz:0,variant:4,serial:1,power:1,duration:.24});fx.update(s,.15);
 const a=fx.ribbons.geometry.getAttribute('position');assert.ok(fx.ribbons.geometry.drawRange.count>0);for(let i=0;i<fx.ribbons.geometry.drawRange.count;i++)assert.ok(a.getX(i)<.775);assert.ok(fx.bloodMotes.every(m=>m.x<.775));
});
test('held guard shows a solid white spark and catches spark on the blade even on Potato, then clears',()=>{
 const {s,fx,v}=fxScene();s.ichor.guarding=true;fx.update(s,.2);fx.update(s,.2);assert.equal(fx.guardSparks.count,1);assert.equal(fx.guardSparks.material.opacity,1);assert.equal(fx.guardSparks.material.color.getHex(),0xffffff);assert.ok(fx.guardSparks.geometry.getAttribute('position').count>=24);const blade=fx.model.getObjectByName('ichor-blade');fx.event({type:'ichorDeflect',id:s.player.id,guard:true,x:.5,z:0,dx:1,dz:0,range:3});const e=fx.ricochets[0],local=blade.worldToLocal(new THREE.Vector3(e.x,e.y-.02,e.z));assert.ok(Math.abs(local.x)<1e-6);assert.ok(local.z>=-1.65&&local.z<=-.26);fx.update(s,.04);assert.ok(fx.lines.count>=14,'contact star and gold sparks');s.ichor.guarding=false;fx.update(s,.4);assert.equal(fx.ricochets.length,0);assert.equal(fx.lines.count,0);assert.equal(fx.guardSparks.count,0);fx.clear();
});
