// Generated by tools/bake-terrain.mjs: every map's prebaked terrain. Do not edit.
import hillTest from './hill-test.js';
import hollowWick from './hollow-wick.js';
export const BAKED_TERRAIN = { 'hill-test': hillTest, 'hollow-wick': hollowWick };
