// Bakes every map's terrain (map.terrain) into the grid the game ships:
// src/maps/terrain/<id>.js, plus the index that lists them. Run after
// changing a map's terrain spec or moving a building that has a baseY:
//   node tools/bake-terrain.mjs
// tests/terrain.test.js fails until you do (it re-bakes and compares).
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { maps } from '../src/maps.js';
import { bakeTerrain, encodeHeights } from '../src/world/terrain-bake.js';

const dir = new URL('../src/maps/terrain/', import.meta.url);
const camel = id => id.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
const baked = [];
for (const map of Object.values(maps)) {
 if (!map.terrain) continue;
 const t0 = performance.now();
 const grid = bakeTerrain(map), data = encodeHeights(grid.heights, grid.cols);
 const text = `// Generated by tools/bake-terrain.mjs from src/maps/${map.id}.js. Do not edit.\n` +
  `// ${grid.cols} x ${grid.rows} heights, 0.5 m apart, in millimetres (world/heightfield.js decodeHeights).\n` +
  `export default { hash: '${grid.hash}', minX: ${grid.minX}, minZ: ${grid.minZ}, cols: ${grid.cols}, rows: ${grid.rows},\n data: '${data}' };\n`;
 const file = new URL(map.id + '.js', dir);
 const old = existsSync(file) ? readFileSync(file, 'utf8') : '';
 if (old !== text) writeFileSync(file, text);
 let lo = Infinity, hi = -Infinity; for (const v of grid.heights) { lo = Math.min(lo, v); hi = Math.max(hi, v); }
 console.log(`${map.id}: ${grid.cols} x ${grid.rows}, ${(lo / 1000).toFixed(2)} to ${(hi / 1000).toFixed(2)} m, ${(data.length / 1024).toFixed(1)} KB, ${(performance.now() - t0).toFixed(0)} ms${old === text ? ' (unchanged)' : ''}`);
 baked.push(map.id);
}
const index = '// Generated by tools/bake-terrain.mjs: every map\'s prebaked terrain. Do not edit.\n' +
 baked.map(id => `import ${camel(id)} from './${id}.js';\n`).join('') +
 `export const BAKED_TERRAIN = { ${baked.map(id => `'${id}': ${camel(id)}`).join(', ')} };\n`;
const indexFile = new URL('index.js', dir);
if (!existsSync(indexFile) || readFileSync(indexFile, 'utf8') !== index) writeFileSync(indexFile, index);
