import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport:{width:1100,height:760}, hasTouch:true });
p.on('pageerror',e=>console.log('ERR',e.message));
await p.goto('http://127.0.0.1:5174/');await p.evaluate(()=>sessionStorage.setItem('deadshift-controls-override','keyboard'));await p.goto('http://127.0.0.1:5174/?play=1&map=deadwater&weapon=rifle&capture=thumbnail'); await p.waitForTimeout(9000);
await p.keyboard.press('KeyW');await p.waitForTimeout(300);console.log('controls',await p.evaluate(()=>document.body.dataset.controls));
const shots=()=>p.evaluate(()=>window.__sim.stats?.launched ?? 0);
await p.evaluate(()=>{const w=document.getElementById('world'),r=w.getBoundingClientRect();const o={pointerId:7,pointerType:'touch',button:0,buttons:1,clientX:r.width*.7,clientY:r.height*.4,bubbles:true,cancelable:true};w.setPointerCapture=()=>{};w.dispatchEvent(new PointerEvent('pointerdown',o));});
await p.waitForTimeout(300); console.log('controls now',await p.evaluate(()=>document.body.dataset.controls));console.log('while held', await p.evaluate(()=>window.__sim.rifle.ammo));
await p.waitForTimeout(600);
await p.evaluate(()=>{const w=document.getElementById('world');window.dispatchEvent(new PointerEvent('pointerup',{pointerId:7,pointerType:'touch',button:0,buttons:0,bubbles:true}));});
await p.waitForTimeout(300); const a=await p.evaluate(()=>window.__sim.rifle.ammo);
await p.waitForTimeout(1500); const c=await p.evaluate(()=>window.__sim.rifle.ammo);
console.log('ammo after lift',a,'1.5s later',c, a===c?'STOPPED':'STILL FIRING');
await b.close();
